# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d9f66f07aef2136fb7712d51ae8293a9cfd94f1c1ac13f00bb2cfc9d5d7785edf674aadc06287b6e8c2e16923dfa050dd28ca50050e95fd79926baa421e4f40

test:
  secret_key_base: 5d435b99db54140576cf0eae758e850317e1fca76cad351ebc37151eb7f23a553f7b3547a0c7f78861ee039e7bbcad6dae67aba77b20026541f833aa773e1393

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
